#!/bin/bash -l
#SBATCH --partition=titanv                                                      #任务提交到titanv分区
#SBATCH --gres=gpu:1                                            #使用4块卡
#SBATCH --nodes=1                                                                       #使用一个节点
#SBATCH --time=1:00:00                                                          #总运行时间，单位小时
#SBATCH --job-name=optimize_F
echo "The current job ID is $SLURM_JOB_ID"                      #从这里开始是执行的脚本
echo "Running on $SLURM_JOB_NUM_NODES nodes:"
echo $SLURM_JOB_NODELIST
echo "Using $SLURM_NTASKS_PER_NODE tasks per node"
nvcc --version
nvidia-smi
echo "A total of $SLURM_NTASKS tasks is used"
echo "CUDA devices $CUDA_VISIBLE_DEVICES"

echo Job started at `date`
python3 optimize.py
echo Job finished at `date`
